### ISSUE TITLE
Laravel Migration Error

### ISSUE THREAD

**Issue by hasandi** [muhazrisofyan/tjetak#1]
Halo,

Gue masih menemukan error terkait migration.

```sh
In Connection.php line 664:
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`)) 
```
```sh
In Connection.php line 458:
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```
Hal ini terjadi karena versi database server yang digunakan oleh Tjetak yaitu MySQL di bawah versi 5.7.7 atau MariaDB di bawah versi 10.2.2, sebagaimana tercantum di https://laravel.com/docs/5.5/migrations#indexes terkait Index Lengths & MySQL / MariaDB.

Solusinya mudah, hanya perlu menambahkan kode berikut di file `AppServiceProvider`:
```php
use Illuminate\Support\Facades\Schema;

/**
 * Bootstrap any application services.
 *
 * @return void
 */
public function boot()
{
  Schema::defaultStringLength(191);
}
```

**Comment by muhazrisofyan** [comment]
Solved
